### ISSUE TITLE
更改优先级会导致支付成功跳回到转首页面

### ISSUE THREAD

**Issue by logChun15** [GZ1903/v2board-theme-LuFly#3]

**Comment by GZ1903** [comment]
或许你的设置出现了问题，你可以创建测试环境进行测试。检查你的配置。

**Comment by GZ1903** [comment]
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/55527553/176800862-0d574c7d-dc79-4e12-8940-28c463c5fa93.png">
检查并没有问题，如果出现问题就应该刚发布就有问题，已经稳定使用许久。
